/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type SchemaVersion = 1;
export type GeneratedAt = string;
export type CollectedAt = string | null;
export type PollSeconds = number;
export type StaleAfterSeconds = number;
export type Status = "ready" | "empty" | "stale" | "unavailable";
export type Ts = string;
export type Equity = number;
export type DailyLimit = number | null;
export type OverallLimit = number | null;
export type Points = EquityPoint[];
export type Ts1 = string;
export type Equity1 = number;
export type Balance = number | null;
export type DailyDdPct = number | null;
export type OverallDdPct = number | null;
export type WindowHours = number;
export type UpdatedAt = string | null;
export type Message = string | null;
export type Status1 = "ready" | "empty" | "stale" | "unavailable";
export type Value = number | null;
export type Soft = number;
export type Hard = number;
export type Limit = number;
export type UpdatedAt1 = string | null;
export type Message1 = string | null;
export type State = "armed" | "idle";
export type ActiveWindow = string | null;
export type ClosesAt = string | null;
export type NextWindow = string;
export type OpensAt = string;
export type Status2 = "ready" | "empty" | "stale" | "unavailable";
export type Data = Trade[] | null;
export type Id = number | null;
export type Timestamp = string | null;
export type Pair = string | null;
export type Direction = string | null;
export type Entry = number | null;
export type StopLoss = number | null;
export type TakeProfit = number | null;
export type ConfluenceScore = number | null;
export type Rr = number | null;
export type Status3 = string | null;
export type RealizedR = number | null;
export type UpdatedAt2 = string | null;
export type Message2 = string | null;
export type Status4 = "ready" | "empty" | "stale" | "unavailable";
export type Data1 = Position[] | null;
export type Id1 = number | null;
export type Pair1 = string | null;
export type Direction1 = string | null;
export type Leg = string | null;
export type Lots = number | null;
export type FloatingPnl = number | null;
export type UpdatedAt3 = string | null;
export type Message3 = string | null;
export type Status5 = "ready" | "empty" | "stale" | "unavailable";
export type Title = string;
export type Currency = string;
export type ScheduledAt = string;
export type Events = NewsEvent[];
export type Pair2 = string;
export type Blocked = boolean | null;
export type Blackout = Blackout1[];
export type UpdatedAt4 = string | null;
export type Message4 = string | null;
export type Status6 = "ready" | "empty" | "stale" | "unavailable";
export type SignalId = number | null;
export type Pair3 = string;
export type Direction2 = string | null;
export type DetectedAt = string | null;
export type Ts2 = string;
export type Open = number;
export type High = number;
export type Low = number;
export type Close = number;
export type Candles = Candle[];
export type Label = string;
export type Kind = "line" | "band";
export type Bottom = number;
export type Top = number;
export type Overlays = Overlay[];
export type MissingEvidence = string[];
export type Source = "recorded" | "historical_context";
export type UpdatedAt5 = string | null;
export type Message5 = string | null;

export interface DashboardSnapshot {
  schema_version: SchemaVersion;
  generated_at: GeneratedAt;
  collected_at: CollectedAt;
  poll_seconds: PollSeconds;
  stale_after_seconds: StaleAfterSeconds;
  equity: PanelEquityData;
  risk: PanelRiskData;
  killzone: Killzone;
  trades: PanelListTrade;
  positions: PanelListPosition;
  news: PanelNewsData;
  setup: PanelSetupData;
}
export interface PanelEquityData {
  status: Status;
  data: EquityData | null;
  updated_at: UpdatedAt;
  message: Message;
}
export interface EquityData {
  points: Points;
  latest: Account | null;
  window_hours: WindowHours;
}
export interface EquityPoint {
  ts: Ts;
  equity: Equity;
  daily_limit: DailyLimit;
  overall_limit: OverallLimit;
}
export interface Account {
  ts: Ts1;
  equity: Equity1;
  balance: Balance;
  daily_dd_pct: DailyDdPct;
  overall_dd_pct: OverallDdPct;
}
export interface PanelRiskData {
  status: Status1;
  data: RiskData | null;
  updated_at: UpdatedAt1;
  message: Message1;
}
export interface RiskData {
  daily: Gauge;
  overall: Gauge;
}
export interface Gauge {
  value: Value;
  soft: Soft;
  hard: Hard;
  limit: Limit;
}
export interface Killzone {
  state: State;
  active_window: ActiveWindow;
  closes_at: ClosesAt;
  next_window: NextWindow;
  opens_at: OpensAt;
}
export interface PanelListTrade {
  status: Status2;
  data: Data;
  updated_at: UpdatedAt2;
  message: Message2;
}
export interface Trade {
  id: Id;
  timestamp: Timestamp;
  pair: Pair;
  direction: Direction;
  entry: Entry;
  stop_loss: StopLoss;
  take_profit: TakeProfit;
  confluence_score: ConfluenceScore;
  rr: Rr;
  status: Status3;
  realized_r: RealizedR;
}
export interface PanelListPosition {
  status: Status4;
  data: Data1;
  updated_at: UpdatedAt3;
  message: Message3;
}
export interface Position {
  id: Id1;
  pair: Pair1;
  direction: Direction1;
  leg: Leg;
  lots: Lots;
  floating_pnl: FloatingPnl;
}
export interface PanelNewsData {
  status: Status5;
  data: NewsData | null;
  updated_at: UpdatedAt4;
  message: Message4;
}
export interface NewsData {
  events: Events;
  blackout: Blackout;
}
export interface NewsEvent {
  title: Title;
  currency: Currency;
  scheduled_at: ScheduledAt;
}
export interface Blackout1 {
  pair: Pair2;
  blocked: Blocked;
}
export interface PanelSetupData {
  status: Status6;
  data: SetupData | null;
  updated_at: UpdatedAt5;
  message: Message5;
}
export interface SetupData {
  signal_id: SignalId;
  pair: Pair3;
  direction: Direction2;
  detected_at: DetectedAt;
  candles: Candles;
  overlays: Overlays;
  missing_evidence: MissingEvidence;
  source: Source;
}
export interface Candle {
  ts: Ts2;
  open: Open;
  high: High;
  low: Low;
  close: Close;
}
export interface Overlay {
  label: Label;
  kind: Kind;
  bottom: Bottom;
  top: Top;
}
